### ISSUE TITLE
Documentation Copypaste Error?

### ISSUE THREAD

**Issue by lyneca** [kostacoffee/SUITSApi#4]
Under the heading for the GET /attendance endpoint:

>Retrieves all attendance. Can be filtered by member and event IDs in the query string. **The request will fail if a record for a given member and event already exists.** If you want to change an existing attendace record, use the PUT endpoint.

Will that really happen?

**Comment by kostacoffee** [comment]
Nice spot. Will remove in a sec :)

**Comment by kostacoffee** [comment]
All fixed now :)
