### ISSUE TITLE
add_attendance 400 Error

### ISSUE THREAD

**Issue by lyneca** [kostacoffee/SUITSApi#5]
The `add_attendance` endpoint throws Bad Requests when provided with the following payload:
```json
{
    "member": 1,
    "event": 3
}
```
I receive this response:
```json
{
    "message": "The browser (or proxy) sent a request that this server could not understand."
}
```
Should this work, or is the request being sent wrong?

**Comment by kostacoffee** [comment]
You need to provide the member and event in the query string. The body of the request should follow the format found here:
https://apidocs.suits.org.au/#tag/attendance%2Fpaths%2F~1attendance%2Fpost

A valid request would be as such:
```
POST /attendance?member=1&event=2
Content-Type: application/json
Authorization: Bearer <token>
{
    "primary": true,
    "secondary": false,
    "additional": ""
}

**Comment by lyneca** [comment]
Gotcha. What are the primary/secondary/additional fields?

**Comment by kostacoffee** [comment]
They're generic fields for attendance.
So if you went to a suits BBQ - got a BBQ and no drink, that's `primary: true` and `secondary: false`. 
Really depends on the context

**Comment by lyneca** [comment]
ah alright
